# Generated by Django 4.2.5 on 2023-09-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='position',
        ),
    ]
